## Data-Source specific properties (now available via config-server)
#spring:
#    datasource:
#        url: jdbc:mysql://localhost:3306/jfsseptkart?rewriteBatchedStatements=true
#        username: root
#        password: manish
#    jpa:
#        show-sql: true
#        hibernate:
#            ddl-auto: update

spring:
    application:
        name: product-catalog

server:
    port: 8082
